services:
  web-server:
    container_name: nubila-web
    image: nginx
    ports:
      - "8080:80"
    user: "${UID}:${GID}"
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./browser/src:/usr/share/nginx/html:ro

  content-server:
    container_name: minio
    image: minio/minio
    env_file:
      - docker/minio.env
    ports: 
      - 9001:9001
    command: server

  bridge-server:
    container_name: nubila-bridge
    image: ubuntu
    ports:
      - "3000:3000"
    environment:
      - SECRET=waitaconnection
    volumes:
      - ./docker/init.sh:/init.sh
      - ./docker/debug.sh:/debug.sh
      - .:/workspace
    entrypoint: /init.sh

  webtorrent-tracker:
    image: node:18
    container_name: tracker
    command: >
      sh -c "npm install -g bittorrent-tracker &&
             bittorrent-tracker --ws --interval 120000"
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"